// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZAjJaViKh8_NWs3qlPTHANQ13u6IhYrk',
    appId: '1:595225681170:android:53624bc94ed8edcbe227cb',
    messagingSenderId: '595225681170',
    projectId: 'taxi-app-d226a',
    storageBucket: 'taxi-app-d226a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAijOuij3KZkvo94X0p14KIADymPGlVB_4',
    appId: '1:595225681170:ios:d4cfa76c00cd81f5e227cb',
    messagingSenderId: '595225681170',
    projectId: 'taxi-app-d226a',
    storageBucket: 'taxi-app-d226a.appspot.com',
    androidClientId: '595225681170-2fn4n67kd2rmpsqv15qc2f4ts8llph7i.apps.googleusercontent.com',
    iosClientId: '595225681170-23agv6ak4lcnjl8phinsl5gaeovv3m9e.apps.googleusercontent.com',
    iosBundleId: 'org.sparcs.taxi-app',
  );
}
