name: Deploy iOS and Android App to App Store and Play Store
on:
  push:
    tags:
      - "v*"

env:
  FLUTTER_VERSION: "3"
  JAVA_VERSION: "11"

jobs:
  release-ios:
    name: Build and release iOS app
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Create .env
        run: |
          echo "FRONT_ADDRESS=https://taxi.sparcs.org" > .env
          echo "BACK_ADDRESS=https://taxi.sparcs.org" >> .env
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.2"
      - name: Create GoogleService-Info.plist
        run: echo '${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}' | base64 --decode > ios/Runner/GoogleService-Info.plist
      - name: Install Fastlane
        run: cd ios && bundle install && cd ..
      - name: Install packages
        run: flutter pub get
      - name: Install pods
        run: cd ios && pod install && cd ..
      - name: Prebuild
        run: flutter build ios --release --no-codesign
      - name: Execute Fastlane command
        run: cd ios && fastlane release type:github
        timeout-minutes: 40
  release-android:
    name: Build and release Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: ${{ env.JAVA_VERSION }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Create .env
        run: |
          echo "FRONT_ADDRESS=https://taxi.sparcs.org" > .env
          echo "BACK_ADDRESS=https://taxi.sparcs.org" >> .env
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.2"
      - name: Create GoogleService-Info.plist
        run: echo '${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}' | base64 --decode > ios/Runner/GoogleService-Info.plist
      - name: Create keystore File from Github Secrets
        run: |
          echo "${{ secrets.ANDROID_KEY_STORE}}" > keystore.b64
          base64 -d -i keystore.b64 > android/app/happycastle.keystore
      - name: Create Service Account JSON from Github Secrets
        run: |
          echo '${{secrets.ANDROID_UPLOAD_GOOGLE_ACOUNT}}' > android/taxi-account.json
      - name: Create Keystore Env
        run: |
          echo "UPLOAD_STORE_FILE=happycastle.keystore" > android/key.properties
          echo "UPLOAD_STORE_PASSWORD=$UPLOAD_STORE_PASSWORD" >> android/key.properties
          echo "UPLOAD_KEY_PASSWORD=UPLOAD_KEY_PASSWORD" >> android/key.properties
          echo "UPLOAD_KEY_ALIAS=UPLOAD_KEY_ALIAS" >> android/key.properties
        env:
          UPLOAD_KEY_ALIAS: ${{ secrets.UPLOAD_KEY_ALIAS }}
          UPLOAD_STORE_PASSWORD: ${{ secrets.UPLOAD_STORE_PASSWORD }}
          UPLOAD_KEY_PASSWORD: $${{secrets.UPLOAD_KEY_PASSWORD }}
      - name: Install Fastlane
        run: cd android && bundle install && cd ..
      - name: Install packages
        run: flutter pub get
      - name: Prebuild
        run: flutter build appbundle
      - name: Execute Fastlane command
        run: cd android && fastlane release
